events { worker_connections 1024; }
http {
    include mime.types;
    server {
        listen 80;
        location /api/v1/ { proxy_pass http://api:8081; }
        location /api/admin/ { proxy_pass http://api:8082; }
        location /static/ { proxy_pass http://api:8081; }
        location /admin { root /usr/share/nginx/html; try_files $uri /admin/index.html; }
    }
}
